# Generated by Django 4.0.2 on 2022-02-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(verbose_name='date added')),
                ('end_time', models.DateTimeField(verbose_name='date ended')),
                ('items', models.IntegerField(default=0)),
                ('available_items', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
